services:
    frontend:
        image: prunplanner-zh:latest
        container_name: prunplanner-zh
        entrypoint: ["sh", "-c"]
        command: >
            "echo \"window.__APP_CONFIG__ = { POSTHOG_KEY: '${POSTHOG_KEY}' }\" > /code/env.js &&
            /bin/go-http-server --port 80 --brotli"
        ports:
            - "8082:80"
        restart: unless-stopped
